---
- name: "Удаление директории и её содержимого"
  hosts: all  # или конкретная группа хостов
  become: yes  # если нужны права root/sudo

  tasks:
    - name: "Проверка существования директории"
      ansible.builtin.stat:
        path: "/home/student/install"  # замените на нужный путь
      register: dir_info

    - name: Размонтирование ISO-образа
      mount:
        path: /tmp/matlab
        state: unmounted

    - name: "Удаление директории (если существует)"
      file:
        path: "/tmp/matlab"
        state: absent

    - name: "Удаление директории (если существует)"
      ansible.builtin.file:
        path: "/home/student/install"  # должен совпадать с указанным выше
        state: absent
      when: dir_info.stat.exists
