---
- name: Set up development environment for students
  hosts: all
  become: true
  roles:
    - role: student
    - role: base_soft
    - role: database
    - role: virt
    - role: docker
    - role: matlab
    - role: pct
    - role: kumir
