---
- name: Configure 30-second sleep timeout
  hosts: localhost
  connection: local
  become: true
  vars:
    SLEEP_TIMEOUT: 30  # 30 секунд
    SLEEP_TYPE: "suspend"

  tasks:
    # 1. Очистка старых настроек
    - name: Remove conflicting settings
      ansible.builtin.file:
        path: /etc/dconf/db/gdm.d/01-power-settings
        state: absent

    # 2. Настройка systemd-logind
#    - name: Configure systemd sleep
#      ansible.builtin.copy:
#        dest: /etc/systemd/logind.conf
#        content: |
#          [Login]
#          IdleAction={{ SLEEP_TYPE }}
#          IdleActionSec={{ SLEEP_TIMEOUT }}s
#        owner: root
#        group: root
#        mode: 0644

    # 3. Настройка GNOME (если используется)
    - name: Set GNOME settings
      ansible.builtin.shell: |
        for USER_HOME in /home/*; do
          USER=$(basename "$USER_HOME")
          if id -u "$USER" >/dev/null 2>&1; then
            sudo -u "$USER" DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u "$USER")/bus \
            gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout {{ SLEEP_TIMEOUT }}
            sudo -u "$USER" DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u "$USER")/bus \
            gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type '{{ SLEEP_TYPE }}'
          fi
        done
      args:
        executable: /bin/bash
      register: gnome_result
      ignore_errors: yes

    # 4. Применение изменений
    - name: Apply settings
      ansible.builtin.service:
        name: systemd-logind
        state: restarted

    # 5. Проверка
    - name: Verify configuration
      ansible.builtin.shell: |
        echo "Systemd: $(busctl get-property org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager IdleActionSec)"
        echo "GNOME: $(sudo -u $SUDO_USER gsettings get org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout)"
      register: verify
      changed_when: false

    - name: Show results
      ansible.builtin.debug:
        var: verify.stdout_lines
