---
- name: Install dependencies
  apt:
    name:
      - "curl"
      - "gnupg"
      - "software-properties-common"
    state: present
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker-ce.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker CE
  apt:
    name:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Add current user to the docker group
  user:
    name: student
    groups: docker
    append: yes

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: "{{ docker_compose_dest }}"
    mode: '0755'

- name: Verify Docker Compose installation
  command: "{{ docker_compose_dest }} --version"
  register: docker_compose_version_output
  changed_when: false

- name: Display Docker Compose version
  debug:
    msg: "{{ docker_compose_version_output.stdout }}"
