name: Ansible Playbook CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Ansible Playbook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: pip install ansible

      - name: Lint with ansible-lint
        run: |
          ansible-lint deploy_software.yml

  deploy:
    name: Run Ansible Playbook
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: pip install ansible

      - name: Run playbook in check mode (dry-run)
        run: ansible-playbook site.yml --check --diff
